---

- name: 'load Ubuntu specific actions'
  include: python-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - base_python
    - ubuntu

- name: 'load Debian specific actions'
  include: python-Debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - base_python
    - debian

- name: 'which pip'
  set_fact:
    pip_executable: "/usr/bin/pip{{ base_python_version }}"

- name: 'load EL specific actions'
  include: python-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - base_python
    - redhat

- name: 'deploy our own pip.conf config file'
  become: yes
  template:
    src: pip.conf.j2
    dest: '/etc/pip.conf'
  tags:
    - base_python
    - pip
