---

- name: 'prepare to get latest setuptools and pip'
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0700
    validate_certs: no
  tags:
    - python

- name: 'load EL specific actions'
  include_tasks: python-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - python
    - redhat

- name: 'load Debian specific actions'
  include_tasks: python-Debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - python
    - debian

- name: 'load Ubuntu specific actions'
  include_tasks: python-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - python
    - ubuntu

- name: 'install latest setuptools and pip'
  become: yes
  command: "{{ base_python_version }} /usr/local/bin/get-pip.py"
  changed_when: no
  tags:
    - python
    - ubuntu
    - skip_ansible_lint  # lint runs before bootstrap

- name: 'make sure directory exists'
  become: yes
  file:
    dest: '/root/.pip'
    state: directory
    owner: root
    group: root
  tags:
    - python
    - pip

- name: 'deploy our own pip.conf config file'
  become: yes
  template:
    src: pip
    dest: '/etc/pip.conf'
  tags:
    - python
    - pip

- name: 'copy requirements.txt'
  copy:
    src: requirements.txt
    dest: '/tmp/python_requirements.txt'
  tags:
    - python
    - pip

- name: 'pip install dependencies'
  pip:
    requirements: '/tmp/python_requirements.txt'
    state: present
  tags:
    - python
    - pip
