---

- name: 'load Ubuntu specific actions'
  include: python-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - base_python
    - ubuntu

- name: 'load Debian specific actions'
  include: python-Debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - base_python
    - debian

- name: 'which pip'
  set_fact:
    pip_executable: "/usr/bin/pip{{ base_python_version }}"

- name: 'load EL specific actions'
  include: python-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - base_python
    - redhat

- name: 'update pip3'
  when: pip_executable == '/usr/bin/pip3'
  command: python3 -m pip install -U pip
  changed_when: false

- name: 'deploy our own pip.conf config file'
  become: true
  template:
    src: pip.conf.j2
    dest: '/etc/pip.conf'
    mode: 0644
  tags:
    - base_python
    - pip

- name: install cryptography
  command: python3 -m pip install -U cryptography
  args:
    # yamllint disable-line rule:line-length
    creates: "{{ my_path }}/usr/local/lib64/{{ python_infix }}/site-packages/cryptography"
  ignore_errors: true  # when redhat scl python is the only one.
  tags:
    - notest
