---

- name: 'load EL specific actions'
  include: python-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - base_python
    - redhat

- name: 'load Debian specific actions'
  include: python-Debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - base_python
    - debian

- name: 'load Ubuntu specific actions'
  include: python-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags:
    - base_python
    - ubuntu

- name: 'install latest setuptools and pip'
  script: get-pip.py
  args:
    creates: "/usr/lib/python2.7/site-packages/pip-{{ python_pip_latest }}.dist-info"
  when: ansible_os_family == 'RedHat'
  changed_when: false  # hack idempotence
  tags:
    - base_python
    - redhat
    - skip_ansible_lint

- name: 'make sure directory exists'
  become: yes
  file:
    dest: '/root/.pip'
    state: directory
    owner: root
    group: root
  tags:
    - base_python
    - pip

- name: 'deploy our own pip.conf config file'
  become: yes
  template:
    src: pip.conf.j2
    dest: '/etc/pip.conf'
  tags:
    - base_python
    - pip

- name: 'copy requirements.txt'
  copy:
    src: requirements.txt
    dest: '/tmp/python_requirements.txt'
  tags:
    - base_python
    - pip

- name: 'pip install dependencies'
  pip:
    requirements: '/tmp/python_requirements.txt'
    state: present
  tags:
    - base_python
    - pip
