---

- name: 'set base_python_version: 3'
  set_fact:
    base_python_version: '3'
    base_python_package: 'python3'
  tags:
    - python
    - pip

- name: 'set base_python_version: 2'
  when: ansible_distribution_release in ['stretch', 'sid']
  set_fact:
    base_python_version: '2'
    base_python_package: 'python2.7'
  tags:
    - python
    - pip

- name: 'set base_python_version: 3'
  when: ansible_distribution_release in ['wheezy']
  set_fact:
    base_python_version: '3'
    base_python_package: 'python3.2'
  tags:
    - python
    - pip

- name: install python3 if available
  become: yes
  apt:
    name: "{{ base_python_package }}"
    state: present
  register: python_install
  until: python_install is success
  retries: 3
  delay: 2
  tags:
    - python
    - pip

- name: ensure apt cache is updated
  apt:
    update_cache: yes
  register: apt_cache_update
  until: apt_cache_update is success
  retries: 3
  delay: 2
  tags:
    - notest

- name: install required packages
  become: yes
  apt:
    name: "{{ python_apts }}"
    state: present
  register: python_apt_install
  until: python_apt_install is success
  retries: 3
  delay: 2
  tags:
    - python
    - pip
