---

- name: 'check if epel repository is installed by base_epel'
  debug:
    var: epel

- name: 'install python_rpms from epel repositories'
  become: true
  when:
    - ansible_distribution_major_version|int <= 7
    - epel is defined
    - not collections_enabled|bool
  yum:
    name: "{{ python_epel }}"
    state: present
    update_cache: true
  register: python_install
  until: python_install is success
  retries: 3
  delay: 2
  tags:
    - base_python
    - pip

- name: 'install centos software collections'
  package:
    name: centos-release-scl-rh
    state: present
  register: scl_install
  until: scl_install is success
  retries: 3
  delay: 2
  when:
    - collections_enabled|bool
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version|int <= 7
  tags:
    - base_python

- name: 'enable rhel software collections'
  # yamllint disable rule:line-length
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  when:
    - collections_enabled|bool
    - ansible_distribution == 'Red Hat Enterprise Linux'
    - ansible_distribution_major_version|int <= 7
  # yamllint enable rule:line-length
  tags:
    - base_python

- name: 'install python27_rpms from rhel software collections'
  become: true
  when:
    - collections_enabled|bool
    - ansible_distribution_major_version|int == 6
  yum:
    name: "{{ python27_rhel }}"
    state: present
    update_cache: true
  register: python27_install
  until: python27_install is success
  retries: 3
  delay: 2
  tags:
    - base_python

- name: 'yum install python from software collections'
  yum:
    name: "{{ python_collection }}"
    state: present
  register: base_python_install
  until: base_python_install is success
  retries: 3
  delay: 2
  when:
    - collections_enabled
    - ansible_distribution_major_version|int == 7
  tags:
    - base_python

- name: 'unlink python3 from software collection'
  file:
    path: "/etc/profile.d/{{ python_collection }}.sh"
    state: absent

- name: 'which pip'
  when: collections_enabled
  set_fact:
    python_infix: python3.8
    pip_executable: "/opt/rh/{{ python_collection }}/root/usr/bin/pip3"
    my_path: "/opt/rh/{{ python_collection }}/root"

- name: 'update pip3'
  when: collections_enabled|bool
  command: "{{ my_path }}/usr/bin/python3 -m pip install -U pip"
  changed_when: false  # for molecule

- name: 'pip3 install cryptography'
  when: collections_enabled|bool
  command: "{{ my_path }}/usr/local/bin/pip3 install cryptography"
  args:
    # yamllint disable-line rule:line-length
    creates: "{{ my_path }}/usr/local/lib64/{{ python_infix }}/site-packages/cryptography"
