---

- name: 'Set  Ubuntu python_version: python3'
  when: ansible_distribution_release in [ 'wheezy', 'xenial', 'jessie', 'sid']
  set_fact:
    base_python_version: '3'
    base_python_package: 'python3.5'
  tags:
    - python
    - pip

- name: 'Install ubuntu python packages'
  become: true
  become_user: root
  apt:
    name: "{{ python_apts }}"
    state: present
    update_cache: true
  register: python_apt_install
  until: python_apt_install is success
  retries: 3
  delay: 2
  tags:
    - python
    - pip
...
