---

- name: 'update setuptools'
  when: base_python_version == 'python2'
  yum:
    name: python-setuptools
    state: latest
  tags:
    - skip_ansible_lint

- name: 'install python_rpms from rhel repositories'
  become: yes
  when:
    - not collections_enabled
    - ansible_distribution_major_version|int == 6
  yum:
    name: "{{ python_rhel }}"
    state: present
    update_cache: yes
  tags:
    - base_python

- name: 'install python_rpms from epel repositories'
  become: yes
  when: 
    - not collections_enabled
    - ansible_distribution_major_version|int == 7
  yum:
    name: "{{ python_epel }}"
    state: present
    update_cache: yes
  tags:
    - base_python
    - pip

- name: 'install centos software collections'
  package:
    name: centos-release-scl-rh
    state: present
  when: collections_enabled and ansible_distribution == 'CentOS'
  tags:
    - base_python

- name: 'enable rhel software collections'
  command: "yum-config-manager --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms"
  when: collections_enabled and  ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - base_python

- name: 'yum install python from software collections'
  yum:
    name: "{{ python_collection }}"
    state: present
  when: collections_enabled
  tags:
    - base_python

- name: 'unlink python3 from software collection'
  file:
    path: "/etc/profile.d/{{ python_collection }}.sh"
    state: absent

- name: 'which pip'
  when: collections_enabled
  set_fact:
    pip_executable: "/opt/rh/{{ python_collection }}/root/usr/bin/pip3"
