---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-python-centos7
    image: centos:7
    privileged: true
  - name: base-python-ubuntu
    image: ubuntu
    privileged: true
  - name: base-python-debian
    image: debian
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
