---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: rh-python36-centos7
    image: centos:7
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
